### ISSUE TITLE
[question] ray not hitting when going through vertex

### ISSUE THREAD

**Issue by zhuker** [nvpro-samples/vk_raytracing_tutorial_KHR#12]
when a ray is tangential to primitive (e.g. passes through one of the vertices)
vulkan nv ray tracer thinks its a miss
embree thinks its a hit
is there a way to force hit in this case?

**Comment by mklefrancois** [comment]
This is a corner case. It would be possible to code an intersection shader to do this, or modify Embree (Open Source) to behave in a similar way.

**Comment by pgautron** [comment]
Hi @zhuker , I would be interested to know more about your use case. Which GPU did you use for this test? And does your acceleration structure involve instance transforms? If you would be able to share a reproducer that would be great. Thanks!

**Comment by zhuker** [comment]
@pgautron 
let me come up with something reproducable

**Comment by mklefrancois** [comment]
Closing, please reopen later with a reproducible.
