### ISSUE TITLE
Are these methods only functional on nvidia graphics cards?

### ISSUE THREAD

**Issue by dzyphr** [nvpro-samples/vk_raytracing_tutorial_KHR#15]
I am wondering If I can follow these tutorials using a 6000 series GPU from AMD or if they are NVIDIA specific.

**Comment by baryluk** [comment]
You can use them and run them on AMD with proper Vulkan driver. They will work on future Intel GPUs with proper drivers too.

**Comment by dzyphr** [comment]
Thank you! I was just worried because of the Nvidia header

**Comment by baryluk** [comment]
@dzyphr Well, they are authored by Nvidia, and there are various shared libraries, and helpers, including various math, vulkan related stuff, and allocator, but it should work on non-Nvidia hardware. I am pretty sure some people used it to release Vulkan games that work in general, and they work on Nvidia, AMD, Intel, and software renderers, etc.

I didn't have yet time to build it or test on 6000 series, but if something doesn't work report :)

PS. I am not affiliated to this repo or nvidia or other gpu makers.
