### ISSUE TITLE
sdk for vulkan vk raytracing ?

### ISSUE THREAD

**Issue by edisonchan** [nvpro-samples/vk_raytracing_tutorial_KHR#16]
https://nvpro-samples.github.io/vk_raytracing_tutorial_KHR/ said there is a SDK 1.2.161 can be download from  https://vulkan.lunarg.com/sdk/home , but latest version over there is 1.2.154.

**Comment by mklefrancois** [comment]
A newer version of the SDK will be soon available. Meanwhile, it is possible to get the headers from https://github.com/KhronosGroup/Vulkan-Headers.

**Comment by edisonchan** [comment]
I had try to copy the "Include\vulkan" and "share\vulkan\registry" from https://github.com/KhronosGroup/Vulkan-Headers and the "vulkan-1.lib" from https://github.com/GPSnoopy/RayTracingInVulkan to replace the installed Vulkan SDK 1.2.154 files from https://vulkan.lunarg.com/sdk/home#windows, but still can not build the project from https://github.com/GPSnoopy/RayTracingInVulkan.

how can I fixed this problem?

the error output like these:

G:\git\RayTracingInVulkan\src\Vulkan\RayTracing\AccelerationStructure.hpp(47,22): error C2065: 'VkAccelerationStructureCreateGeometryTypeInfoKHR': undeclared identifie

r (compiling source file G:\git\RayTracingInVulkan\src\Vulkan\RayTracing\AccelerationStructure.cpp) [G:\git\RayTracingInVulkan\build\windows\src\RayTracer.vcxproj]

G:\git\RayTracingInVulkan\src\Vulkan\RayTracing\AccelerationStructure.hpp(47,15): error C2923: 'std::vector': 'VkAccelerationStructureCreateGeometryTypeInfoKHR' is not

a valid template type argument for parameter '_Ty' (compiling source file G:\git\RayTracingInVulkan\src\Vulkan\RayTracing\AccelerationStructure.cpp) [G:\git\RayTracin

gInVulkan\build\windows\src\RayTracer.vcxproj]

**Comment by akeley98** [comment]
The installer for Vulkan SDK version 1.2.162.0 has been publicly released, try that, it should work more smoothly than manual installation. If it's still not working, check your VULKAN_SDK environment variable and see that it points to the correct directory. I'm on Linux so I don't know the exact directory but it should have "1.2.162" in its name.

**Comment by mklefrancois** [comment]
Link to the SDK: https://vulkan.lunarg.com/sdk/home#windows

Environment variables
~~~~
VULKAN_SDK=C:\VulkanSDK\1.2.162.0
VK_LAYER_PATH=C:\VulkanSDK\1.2.162.0\Bin
VK_SDK_PATH=C:\VulkanSDK\1.2.162.0
~~~~
