### ISSUE TITLE
Build issue with VS2019

### ISSUE THREAD

**Issue by SirKnightTG** [nvpro-samples/vk_raytracing_tutorial_KHR#2]
Using the vulkan driver, latest Vulkan-Headers and glslang, as the tutorial mentions, I am seeing the following errors in all projects:

1>------ Build started: Project: vk_ray_tracing__simple_KHR, Configuration: Debug x64 ------
1>hello_vulkan.cpp
1>D:\Programming\Vulkan\shared_sources\nvvkpp/pipeline_vkpp.hpp(91,1): error C2440: 'return': cannot convert from 'vk::ResultValue<vk::Pipeline>' to 'vk::Pipeline'
1>D:\Programming\Vulkan\shared_sources\nvvkpp/pipeline_vkpp.hpp(91,1): message : No constructor could take the source type, or constructor overload resolution was ambiguous

**Comment by SirKnightTG** [comment]
Yes, it seems this is the same issue. I used the vulkan.hpp you linked and it works. Thanks!

**Comment by NeilBickford-NV** [comment]
No problem, glad it worked!
