### ISSUE TITLE
ray_tracing_intersection - says add hitAttributeEXT to raytrace.rint but it's not there

### ISSUE THREAD

**Issue by richardeakin** [nvpro-samples/vk_raytracing_tutorial_KHR#20]
Hi,

I've been following these tutorials and first off wanted to say thanks so much! They are an excellent way to learn about this pretty sophisticated domain.

  I wanted to point out something that has me scratching my head in the _ray_tracing_intersection_ tutorial - it mentions the need for the following line in [this](https://github.com/nvpro-samples/vk_raytracing_tutorial_KHR/tree/master/ray_tracing_intersection#raytracerint) section:

```
hitAttributeEXT vec3 HitAttribute;
```

However I don't see it in the intersection shader, `hitAttributeEXT` is only used within the closest hit shader. Is this an artifact of the previous version of the spec?

Thanks again for the great tutorials,
Rich

**Comment by mklefrancois** [comment]
Hi @richardeakin, you are right, this is a left over from previous spec. I will remove it from the tutorial. 

And thanks for the comments, really appreciated that it helped you.

**Comment by mklefrancois** [comment]
Fixed in https://github.com/nvpro-samples/vk_raytracing_tutorial_KHR/commit/9a174a8269abff96a8d0416e23e9556c1930f9c9
