### ISSUE TITLE
Errata: NVIDIA Vulkan Ray Tracing Tutorial: 5 Acceleration Structure

### ISSUE THREAD

**Issue by cpope9141** [nvpro-samples/vk_raytracing_tutorial_KHR#31]
Thank you for this thorough tutorial. I have found the following errors in the introductory section to chapter 5:

nvvk::RaytracingBuilder m_rtBuilder; -> nvvk::**RaytracingBuilderKHR** m_rtBuilder;

m_rtBuilder.setup(m_device, m_alloc, m_graphicsQueueIndex); -> m_rtBuilder.setup(m_device, **&m_alloc**, m_graphicsQueueIndex);

**Comment by mklefrancois** [comment]
Thanks @cpope9141 for bringing up those errors. All fixed.
