### ISSUE TITLE
Incorrect vulkan object name was mentioned in the tutorial

### ISSUE THREAD

**Issue by Erfan-Ahmadi** [nvpro-samples/vk_raytracing_tutorial_KHR#33]
It should be `VkPipelineShaderStageCreateInfo` instead of `VkPipelineStageCreateInfo`

It also occured in 3 other places in the text

https://github.com/nvpro-samples/vk_raytracing_tutorial_KHR/blob/d66243800cf497a16dce555684e750917cbb7307/docs/vkrt_tutorial.md.html#L1070

**Comment by mklefrancois** [comment]
Thanks for pointing those issues. It will be fixed in the next update.

**Comment by NeilBickford-NV** [comment]
Looks like this is fixed now in 3e399a - [line 1110](https://github.com/nvpro-samples/vk_raytracing_tutorial_KHR/blame/master/docs/vkrt_tutorial.md.html#L1110) now says

```
At this point, the shader groups reference individual shaders by their index in the above `VkPipelineShaderStageCreateInfo`
```

Thanks again!
