### ISSUE TITLE
Invalid comment regarding the type of vertex data

### ISSUE THREAD

**Issue by m-radomski** [nvpro-samples/vk_raytracing_tutorial_KHR#34]
Hi,

I think it should be `vec4` since we are defining a `VK_FORMAT_R32G32B32A32_SFLOAT` with 4 components. And because of that the comment is somewhat misleading.

https://github.com/nvpro-samples/vk_raytracing_tutorial_KHR/blob/d66243800cf497a16dce555684e750917cbb7307/docs/vkrt_tutorial.md.html#L299

**Comment by mklefrancois** [comment]
Thank you for reporting this. The vertex position is really a vec3, and therefore the vertexFormat should be `VK_FORMAT_R32G32B32_SFLOAT`. Fortunately the fourth component is ignored. I will fix this in this tutorial and the other ones as well.
