### ISSUE TITLE
ray_tracing_ao  crash

### ISSUE THREAD

**Issue by wiltchamberian** [nvpro-samples/vk_raytracing_tutorial_KHR#35]
on my win7 x64 pc , with the Vulkan SDK 1.2.162.1  with Visual Studio 2019 Debug x64
when I  run the ray_tracing_ao demo,
it crash at:  void HelloVulkan::createCompPipelines() 
VkResult res = vkCreateComputePipelines(m_device, {}, 1, &cpCreateInfo, nullptr, &m_compPipeline);

in this function ,it crashes.

**Comment by NeilBickford-NV** [comment]
Hi yao tang!

I've just verified that the latest version should work (my system has Vulkan SDK 1.2.189 and NV driver 471.55) - could you give me more information about the system you're running on and the crash? Specifically,
- What GPU are you using?
- What GPU driver version are you using?
- Would it be possible to get a [minidump](https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem-minidumps?view=vs-2019) when it runs into the crash?

Thanks!

**Comment by mklefrancois** [comment]
@wiltchamberian, it works also for me, but I'm also using 1.2.189.0 and a very recent video driver. The graphic card is GeForce RTX 3060 Ti, which is supporting `VK_KHR_ray_query`. If you have all of the above and still fails, check if the shader is compiled and loaded one line above.
```
  cpCreateInfo.stage = nvvk::createShaderStageInfo(m_device, nvh::loadFile("spv/ao.comp.spv", true, defaultSearchPaths, true),
                                                   VK_SHADER_STAGE_COMPUTE_BIT);
```
