### ISSUE TITLE
ray_tracing_ao crashes when Nsight is used 

### ISSUE THREAD

**Issue by kyamant** [nvpro-samples/vk_raytracing_tutorial_KHR#43]
I've tried to get a better understanding of the **ray_tracing_ao** example by examining the sample in Nsight (version **2022.4.1**), however the application crashes on compute pipeline creation. I tried launching Nsight from VS 2022 as well as independently.

 Minidump file [18c783f7-5489-4713-a27c-e26c5ef30ee7.zip](https://github.com/nvpro-samples/vk_raytracing_tutorial_KHR/files/9678549/18c783f7-5489-4713-a27c-e26c5ef30ee7.zip)

> Reason:    EXCEPTION_ACCESS_VIOLATION_READ
> Address:   0xffffffffffffffff
> Assertion: Unknown assertion type 0x00000000
> 
> Thread 0 (crashed)
>  [0]  nvoglv64.dll + 0x8661e
>  [1]  nvoglv64.dll + 0x142644d
>  [2]  nvoglv64.dll + 0x14589c2
>  [3]  nvoglv64.dll + 0x92aa2
>  [4]  nvoglv64.dll + 0xa9430
>  [5]  nvoglv64.dll + 0xa34f0
>  [6]  nvoglv64.dll + 0x29d67a0
>  [7]  nvoglv64.dll + 0xa2a86
>  [8]  nvoglv64.dll + 0xe2d901
>  [9]  nvoglv64.dll + 0x695aa
>  [10]  nvoglv64.dll + 0x69383
>  [11]  nvoglv64.dll + 0x11378f
> 
> Thread 1
>  [0]  ntdll.dll + 0xa0994
>  [1]  ntdll.dll + 0x52dc7
> 
> Thread 2
>  [0]  ntdll.dll + 0xa0994
>  [1]  ntdll.dll + 0x52dc7
> 
> Thread 3
>  [0]  ntdll.dll + 0xa0994
>  [1]  ntdll.dll + 0x52dc7
> 
> Thread 4
>  [0]  ntdll.dll + 0x9d064
>  [1]  KERNELBASE.dll + 0x61a7f
>  [2]  ntdll.dll + 0x507b0
>  [3]  Nvda.Graphics.Interception.dll + 0x3eb4e20
>  [4]  ntdll.dll + 0x25ba1
>  [5]  Nvda.Graphics.Interception.dll + 0x2a83400
>  [6]  Nvda.Graphics.Interception.dll + 0x42e8100
>  [7]  ntdll.dll + 0x247b1
>  [8]  ucrtbase.dll + 0xf05b
>  [9]  Nvda.Graphics.Interception.dll + 0x3002dd7
>  [10]  Nvda.Graphics.Interception.dll + 0x42e8100
>  [11]  Nvda.Graphics.Interception.dll + 0x30036fe
>  [12]  Nvda.Graphics.Interception.dll + 0x3003c95
>  [13]  ntdll.dll + 0x302c9
>  [14]  Nvda.Graphics.Interception.dll + 0x3f01750
>  [15]  Nvda.Graphics.Interception.dll + 0x3bd1d50
>  [16]  Nvda.Graphics.Interception.dll + 0x300388a
>  [17]  Nvda.Graphics.Interception.dll + 0x30030f3
>  [18]  Nvda.Graphics.Interception.dll + 0x2bd1f20
>  [19]  Nvda.Graphics.Interception.dll + 0x2bd1f2f
>  [20]  Nvda.Graphics.Interception.dll + 0x2b02d18
>  [21]  Nvda.Graphics.Interception.dll + 0x2bd1f05
>  [22]  Nvda.Graphics.Interception.dll + 0x4abc668
>  [23]  Nvda.Graphics.Interception.dll + 0x2bd1f20
>  [24]  Nvda.Graphics.Interception.dll + 0x4abc668
>  [25]  KERNELBASE.dll + 0x76601
>  [26]  Nvda.Graphics.Interception.dll + 0x2bd2c0a
>  [27]  ucrtbase.dll + 0x21bb2
>  [28]  kernel32.dll + 0x17034
>  [29]  ntdll.dll + 0x52651
> 
> Thread 5
>  [0]  ntdll.dll + 0x9da94
>  [1]  KERNELBASE.dll + 0x4cbc0
>  [2]  ntdll.dll + 0x52630
> 
> Thread 6
>  [0]  ntdll.dll + 0xa0994
>  [1]  ntdll.dll + 0x52dc7
> 
> Thread 7
>  [0]  ntdll.dll + 0xa0994
>  [1]  ntdll.dll + 0x52dc7
> 
> Thread 8
>  [0]  ntdll.dll + 0x9da94
>  [1]  KERNELBASE.dll + 0x4cbc0
>  [2]  ucrtbase.dll + 0x15efa
>  [3]  CoreMessaging.dll + 0xa2461
>  [4]  CoreMessaging.dll + 0xa2464
>  [5]  inputhost.dll + 0x135b98
>  [6]  inputhost.dll + 0xbb20
>  [7]  inputhost.dll + 0xb3eb
>  [8]  CoreMessaging.dll + 0xa246d
>  [9]  CoreMessaging.dll + 0x18a78
>  [10]  CoreMessaging.dll + 0x160f4
>  [11]  inputhost.dll + 0x2f4e
>  [12]  CoreMessaging.dll + 0xa7ff0
>  [13]  inputhost.dll + 0xb3eb
>  [14]  CoreMessaging.dll + 0x18a78
>  [15]  CoreMessaging.dll + 0x160f4
>  [16]  Nvda.Graphics.Interception.dll + 0x28f8db4
>  [17]  Nvda.Graphics.Interception.dll + 0x2b78438
>  [18]  CoreMessaging.dll + 0x3cd53
>  [19]  CoreMessaging.dll + 0x17fff
>  [20]  CoreMessaging.dll + 0x1f6b6
>  [21]  CoreMessaging.dll + 0x14cf5
>  [22]  CoreMessaging.dll + 0x17ce9
>  [23]  CoreMessaging.dll + 0x17471
>  [24]  CoreMessaging.dll + 0x58921
>  [25]  CoreMessaging.dll + 0x1b35a
>  [26]  CoreMessaging.dll + 0x3d0dd
>  [27]  CoreMessaging.dll + 0x16744
>  [28]  CoreMessaging.dll + 0x18100
>  [29]  CoreMessaging.dll + 0x1c04a
>  [30]  CoreMessaging.dll + 0xb28d8
>  [31]  CoreMessaging.dll + 0x1996b
>  [32]  CoreMessaging.dll + 0x111a8
>  [33]  ntdll.dll + 0x247b1
>  [34]  CoreMessaging.dll + 0x30312
>  [35]  CoreMessaging.dll + 0x1ae80
>  [36]  CoreMessaging.dll + 0x458af
>  [37]  CoreMessaging.dll + 0x16c28
>  [38]  CoreMessaging.dll + 0x587f3
>  [39]  CoreMessaging.dll + 0x12198
>  [40]  inputhost.dll + 0xebcc0
>  [41]  CoreMessaging.dll + 0x4ebf5
>  [42]  CoreMessaging.dll + 0x4da7b
>  [43]  msvcp_win.dll + 0xf7e2
>  [44]  inputhost.dll + 0x125aa
>  [45]  inputhost.dll + 0x167f9
>  [46]  kernel32.dll + 0x17034
>  [47]  ntdll.dll + 0x52651
> 
> Thread 9
>  [0]  ntdll.dll + 0x9da94
>  [1]  KERNELBASE.dll + 0x4cbc0
> 
> Thread 10
>  [0]  ntdll.dll + 0xa0994
>  [1]  ntdll.dll + 0x52dc7
> 
> Thread 11
>  [0]  ntdll.dll + 0x9cfc4
>  [1]  KERNELBASE.dll + 0x21ace
>  [2]  Nvda.Graphics.Interception.dll + 0x28f8db4
>  [3]  ntdll.dll + 0x247b1
>  [4]  Nvda.Graphics.Interception.dll + 0x2b785e2
>  [5]  Nvda.Graphics.Interception.dll + 0x2b78508
>  [6]  nvoglv64.dll + 0x125e57a
>  [7]  nvoglv64.dll + 0xdc6e80
>  [8]  nvoglv64.dll + 0xdc65ba
>  [9]  nvoglv64.dll + 0x1212c52
>  [10]  nvoglv64.dll + 0xdc7e78
>  [11]  kernel32.dll + 0x17034
>  [12]  ntdll.dll + 0x52651
> 
> Thread 12
>  [0]  ntdll.dll + 0x9cfc4
>  [1]  KERNELBASE.dll + 0x21ace
>  [2]  Nvda.Graphics.Interception.dll + 0x28f8db4
>  [3]  nvoglv64.dll + 0xe2d97e
>  [4]  Nvda.Graphics.Interception.dll + 0x2b785e2
>  [5]  nvoglv64.dll + 0xdc5514
>  [6]  nvoglv64.dll + 0x122c1be
>  [7]  Nvda.Graphics.Interception.dll + 0x2b78508
>  [8]  nvoglv64.dll + 0x122ddd0
>  [9]  nvoglv64.dll + 0xdc65ba
>  [10]  nvoglv64.dll + 0x122f4e2
>  [11]  nvoglv64.dll + 0xdc7e78
>  [12]  kernel32.dll + 0x17034
>  [13]  ntdll.dll + 0x52651
> 
> Thread 13
>  [0]  ntdll.dll + 0x9cfc4
>  [1]  KERNELBASE.dll + 0x21ace
>  [2]  Nvda.Graphics.Interception.dll + 0x28f8db4
>  [3]  nvoglv64.dll + 0xe2d97e
>  [4]  Nvda.Graphics.Interception.dll + 0x2b785e2
>  [5]  nvoglv64.dll + 0xdc5514
>  [6]  nvoglv64.dll + 0xe6457b
>  [7]  Nvda.Graphics.Interception.dll + 0x2b78508
>  [8]  nvoglv64.dll + 0xe61f8a
>  [9]  nvoglv64.dll + 0xdc65ba
>  [10]  nvoglv64.dll + 0x121dca2
>  [11]  nvoglv64.dll + 0xa59d6c
>  [12]  nvoglv64.dll + 0xdc7e78
>  [13]  kernel32.dll + 0x17034
>  [14]  ntdll.dll + 0x52651
> 
> Thread 14
>  [0]  ntdll.dll + 0x9da94
>  [1]  KERNELBASE.dll + 0x4cbc0
>  [2]  ntdll.dll + 0x19877
>  [3]  nvrtum64.dll + 0x28685a
>  [4]  nvrtum64.dll + 0x286e29
>  [5]  ntdll.dll + 0x19aae
>  [6]  ntdll.dll + 0x19a26
>  [7]  ntdll.dll + 0x3e683
>  [8]  nvrtum64.dll + 0x89450
>  [9]  ntdll.dll + 0x5d964
>  [10]  ntdll.dll + 0x16c4d0
>  [11]  ntdll.dll + 0x51d9c
>  [12]  nvrtum64.dll + 0x89450
>  [13]  ntdll.dll + 0x17955
>  [14]  ntdll.dll + 0x16c4d0
>  [15]  ntdll.dll + 0x51748
>  [16]  ntdll.dll + 0x1a8fc
>  [17]  ntdll.dll + 0x172000
>  [18]  ntdll.dll + 0x174a24
>  [19]  ntdll.dll + 0x147648
>  [20]  ntdll.dll + 0x69706
>  [21]  Nvda.Graphics.Interception.dll + 0x28f8db4
>  [22]  ntdll.dll + 0x69552
>  [23]  ntdll.dll + 0x25ba1
>  [24]  Nvda.Graphics.Interception.dll + 0x2b78438
>  [25]  ntdll.dll + 0x515e2
>  [26]  ntdll.dll + 0x32228
>  [27]  Nvda.Graphics.Interception.dll + 0x28f8db4
>  [28]  KERNELBASE.dll + 0x4cabe
>  [29]  KERNELBASE.dll + 0x687fb
>  [30]  Nvda.Graphics.Interception.dll + 0x2b7835d
>  [31]  apphelp.dll + 0xe4ec
>  [32]  ntdll.dll + 0x301a7
>  [33]  nvcuda64.dll + 0x28ee83
>  [34]  nvcuda64.dll + 0x1e4754
>  [35]  kernel32.dll + 0x17034
>  [36]  ntdll.dll + 0x52651
>  [37]  ntdll.dll + 0x334f1
>  [38]  nvcuda64.dll + 0x55a1b8
>  [39]  ntdll.dll + 0x302c9
>  [40]  kernel.appcore.dll + 0x3100
>  [41]  nvcuda64.dll + 0x52bb4e
>  [42]  ntdll.dll + 0x3e25f
>  [43]  kernel.appcore.dll + 0x3100
>  [44]  nvcuda64.dll + 0x52bb4e
>  [45]  Nvda.Graphics.Interception.dll + 0x28f8de4
>  [46]  nvcuda64.dll + 0x1f4086
>  [47]  nvcuda64.dll + 0x79832
>  [48]  nvcuda64.dll + 0x28f2dd
>  [49]  nvcuda64.dll + 0x1e4123
>  [50]  nvcuda64.dll + 0x520404
>  [51]  kernel32.dll + 0x17034
>  [52]  ntdll.dll + 0x52651
> 
> Thread 15
>  [0]  win32u.dll + 0xa104
>  [1]  user32.dll + 0x2078e
>  [2]  Nvda.Graphics.Interception.dll + 0x2b77a78
>  [3]  user32.dll + 0xe703
>  [4]  Nvda.Graphics.Interception.dll + 0x2b77998
>  [5]  user32.dll + 0x4f551
>  [6]  nvoglv64.dll + 0xdbedcf
>  [7]  kernel32.dll + 0x17034
>  [8]  ntdll.dll + 0x52651

**Comment by mklefrancois** [comment]
The issue isn't fixed yet, but there is a workaround. Go under Troubleshooting, and set "Collect Line Tables" to **No**
![image](https://user-images.githubusercontent.com/38076163/203528346-c61aabe6-113b-4b71-8838-e38dd81400f8.png)
