### ISSUE TITLE
Fix raytrace.rgen in ray_tracing__advance

### ISSUE THREAD

**Issue by lukelmy** [nvpro-samples/vk_raytracing_tutorial_KHR#44]
According to ray_tracing_jitter_cam, we should write directly to the image if the frame number is equal to 0 in "raytrace.rgen".
<img width="330" alt="ray_tracing_jitter_cam_shaders_raytrace rgen" src="https://user-images.githubusercontent.com/116545142/203249086-e83508d4-0d05-446d-95b5-b5882b8a4d46.png">
However, there is an equal sign in "raytrace.rgen" of ray_tracing__advance, which may cause corruption. 
<img width="480" alt="ray_tracing__advance_shaders_raytrace rgen" src="https://user-images.githubusercontent.com/116545142/203249093-c89dd15d-9252-479a-aeb8-5a0109d695de.png">

**Comment by mklefrancois** [comment]
Thanks for reporting the issue. It works because when `pcRay.frame ==0`, `a` will be equal to `1.0F` and the image will store only `prd.hitValue`. But to avoid any confusion and the unnecessary `imageLoad`, the code will be changed.
