### ISSUE TITLE
Incorrect srcStageMask in vkCmdPipelineBarrier in ray_tracing_ao

### ISSUE THREAD

**Issue by lukelmy** [nvpro-samples/vk_raytracing_tutorial_KHR#45]
In ray_tracing_ao, g-buffer is drawn in fragment shader and sampled in compute shader. Between both shaders there is a pipeline barrier. According to vulkan specs, the srcStageMask should be VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT instead of VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT which may cause corruption sometimes.

> VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT specifies the stage of the pipeline after blending where the final color values are output from the pipeline. This stage also includes [subpass load and store operations](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap8.html#renderpass-load-store-ops), multisample resolve operations for framebuffer attachments with a color or depth/stencil format, and [vkCmdClearAttachments](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap19.html#vkCmdClearAttachments).

https://github.com/nvpro-samples/vk_raytracing_tutorial_KHR/blob/003bab42a58fd028a20f7c307ca991a1b5a6f48c/ray_tracing_ao/hello_vulkan.cpp#L810

**Comment by lukelmy** [comment]
Also "imgMemBarrier.srcAccessMask = VK_ACCESS_SHADER_WRITE_BIT" should be added before L829.
https://github.com/nvpro-samples/vk_raytracing_tutorial_KHR/blob/003bab42a58fd028a20f7c307ca991a1b5a6f48c/ray_tracing_ao/hello_vulkan.cpp#L829-L830

**Comment by mklefrancois** [comment]
Thanks for spotting this @lukelmy , the change was committed in 525becc66ca5c27309560192ecc0db435959532d
