### ISSUE TITLE
Second rmiss shader defined too early in the tutorial

### ISSUE THREAD

**Issue by Scurek** [nvpro-samples/vk_raytracing_tutorial_KHR#46]
Second miss shader, which will later be used for shadows, is already declared in the step 7.1. I assume this is not intended as the number of miss shaders is set to 1 and its enum (eMiss2) is not defined at the time.

**Comment by mklefrancois** [comment]
Thanks, this has been corrected in c213e3b88ed1119ea8f2b88a66cde8e88141ed8f
