### ISSUE TITLE
add new simple sample showing usage of Ada SER functionality (via new VK NV SER ext)

### ISSUE THREAD

**Issue by oscarbg** [nvpro-samples/vk_raytracing_tutorial_KHR#49]

**Comment by NeilBickford-NV** [comment]
Hi @oscarbg ! You might be interested in the ser_pathtrace sample within nvpro-samples/vk_mini_samples here: https://github.com/nvpro-samples/vk_mini_samples/tree/main/samples/ser_pathtrace .

Thanks!
