### ISSUE TITLE
updateBlas missing in animationObject

### ISSUE THREAD

**Issue by nibeh** [nvpro-samples/vk_raytracing_tutorial_KHR#5]
Thanks for the nice tutorial codes!
According to the documentation (https://nvpro-samples.github.io/vk_raytracing_tutorial_KHR/vkrt_tuto_animation.md.htm) we need to update the BLAS at the end of void HelloVulkan::animationObject(float time), however I cannot find the reference in the code. As animationInstances (which updates the blas(?)) is called before, we have a delay of one frame in the animation of the sphere - am I correct?

**Comment by mklefrancois** [comment]
Hi nibeh,

The documentation is fine, but the code has the `m_rtBuilder.updateBlas(2);` in the wrong function. It should be at the end of `HelloVulkan::animationObject()` instead of `HelloVulkan::animationInstances()`

Thanks for reporting, this should be corrected soon.

**Comment by mklefrancois** [comment]
Done in:
https://github.com/nvpro-samples/vk_raytracing_tutorial_KHR/commit/e6976c0e65df43b58ce9bd641ea51cdcf6fb2129
