### ISSUE TITLE
What does Nb mean?

### ISSUE THREAD

**Issue by FuXiii** [nvpro-samples/vk_raytracing_tutorial_KHR#53]
When I read is tutorial some code, such like:

```CPP
uint32_t maxPrimitiveCount = model.nbIndices / 3;
triangles.maxVertex = model.nbVertices;
uint32_t nbCompactions{0};   // Nb of BLAS requesting compaction
```
The `nb` in code `nbIndices`, `nbVertices` and `nbCompactions`.

What does `nb` mean?

**Comment by mklefrancois** [comment]
Nb is an abbreviation for number. In this case, it is the number of vertices, of indices, …

**Comment by FuXiii** [comment]
Thanks
