### ISSUE TITLE
vkGetBufferDeviceAddress could not be located

### ISSUE THREAD

**Issue by sidshekar** [nvpro-samples/vk_raytracing_tutorial_KHR#6]
Hi,

I am able to create the project but when I run any of the samples I get this error.

I am not sure what is causing it.

![image](https://user-images.githubusercontent.com/2862097/83314046-baa89700-a26c-11ea-9c9a-ddaa65e5e7f2.png)

Kindly help. thanks,

**Comment by NeilBickford-NV** [comment]
Hi sidshekar,

My first guess is that this might point to Vulkan being linked into the application incorrectly - could you let me know which version of the Vulkan API you're using, as well as if CMake printed out any error or warning messages during configuration?

Thanks!

**Comment by sidshekar** [comment]
Hi, the vulkan version being used is 1.2.135.0. No CMAKE didnt give an error/warninhg during configuration. 

![image](https://user-images.githubusercontent.com/2862097/83315019-74a20200-a271-11ea-8fe3-b8b2ba8046aa.png)

**Comment by NeilBickford-NV** [comment]
Hmm - looks like I can repro the problem here as well! Oddly enough, it looks like `vkGetBufferDeviceAddress` is the only symbol it can't find in `C:\Windows\system32\vulkan-1.dll`, which is very odd.

**Comment by sidshekar** [comment]
Yes that is strange indeed. Should I use a previous version of SDK then?

**Comment by NeilBickford-NV** [comment]
I don't think so - `vk_device_generated_cmds` uses `vkGetBufferDeviceAddressEXT` (which it manually loads), so it's probably an issue with the sample itself or the Vulkan headers. Tagging in @mklefrancois to see if he can take a look at it next week in case I can't figure it out today!

**Comment by NeilBickford-NV** [comment]
OK, I'm still not totally sure why this is the case and am unfortunately out of time for the week, but it looks like the application should load if you replace all instances of `vkGetBufferDeviceAddress` with `vkGetBufferDeviceAddressKHR` in `raytraceKHR_vk.cpp`!

**Comment by sidshekar** [comment]
Ok thanks! Ill try.

**Comment by sidshekar** [comment]
After replacing vkGetBufferDeviceAddress with vkGetBufferDeviceAddressKHR in raytraceKHR_vk.hpp now I get a runtime error.


![image](https://user-images.githubusercontent.com/2862097/83316694-6822a700-a27b-11ea-8227-caa6490e7df5.png)

Says compatible devices 0. I am running a RTX 2080.

![image](https://user-images.githubusercontent.com/2862097/83316712-8b4d5680-a27b-11ea-8e07-0be25c23939d.png)

**Comment by NeilBickford-NV** [comment]
That's interesting - maybe try using the [non-KHR](https://github.com/nvpro-samples/vk_raytracing_tutorial) raytracing tutorial while we work this out?

Thanks again!

**Comment by sidshekar** [comment]
Thanks. I tried that one as well. It has an issue with creating Shader Binding Table!!.

![image](https://user-images.githubusercontent.com/2862097/83317870-4843b100-a284-11ea-8643-c48f2c89eac9.png)

**Comment by mklefrancois** [comment]
Hi,

I just have tried and I don't see the issue you are mentioning in the KHR tutorial. Please make sure to install the latest **Vulkan 1.2 BETA**  driver (443.24). https://developer.nvidia.com/vulkan-driver

Regarding the other issue you are seeing with the NV tutorial, the problem resides in the vulkan.hpp. The screenshot shows that the function `getRayTracingShaderGroupHandlesNV` calls `getRayTracingShaderGroupHandlesKHR` and this one is NULL as it is not part of the extensions added on the creation of the device. To fix this, you can modify vulkan.hpp to call the NV version instead of the KHR. There are a few of those in the 1.2.135 version of the SDK, and is fixed on GitHub.

**Comment by sidshekar** [comment]
Ok. Thanks for letting me know. I’ll try installing the beta drivers.

**Comment by mklefrancois** [comment]
Please let me know if the KHR version works for you. It is the newest version of the tutorial and contains the latest fixes. Note that the non-beta driver doesn't have all symbols, this might be why it was not working for you.

**Comment by sidshekar** [comment]
Hi! Ya the KHR samples work after installing the beta drivers. I wasnt sure if the beta drivers were still required as it is say anywhere on the tutorial. thanks!!
