### ISSUE TITLE
gl_LaunchSizeEXT corresponds to the image size provided when calling traceRayEXT

### ISSUE THREAD

**Issue by FuXiii** [nvpro-samples/vk_raytracing_tutorial_KHR#60]
In [11.1 Ray generation (raytrace.rgen)](https://nvpro-samples.github.io/vk_raytracing_tutorial_KHR/#cameramatrices/raygeneration(raytrace.rgen)) :

> *`gl_LaunchSizeEXT` corresponds to the image size provided when calling `traceRayEXT`*

In [GLSL_EXT_ray_tracing](https://github.com/KhronosGroup/GLSL/blob/883a2113d8ab3cbf0cc534989a90ba1bb0ba6a11/extensions/ext/GLSL_EXT_ray_tracing.txt#L716) :

> *The input variable gl_LaunchSizeEXT is available in the ray generation, intersection, any-hit, closest-hit, miss, and callable languages to specify the <width> and <height> and <depth> dimensions passed into a `vkCmdTraceRaysKHR` call.*

Maybe we need change  `traceRayEXT` to `vkCmdTraceRaysKHR`?

**Comment by NeilBickford-NV** [comment]
Yes, I believe this is a typo; I'll make an edit to fix it. Thanks!

**Comment by NeilBickford-NV** [comment]
Fixed in https://github.com/nvpro-samples/vk_raytracing_tutorial_KHR/commit/9b84682b16733a72528b72d8dce818c7f373d22e; thanks again!
