### ISSUE TITLE
issue on win10 when cmake

### ISSUE THREAD

**Issue by Hoshino-Ruri** [nvpro-samples/vk_raytracing_tutorial_KHR#69]
cmake ..
-- Building for: Visual Studio 17 2022
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19045.
-- The C compiler identification is MSVC 19.38.33134.0
-- The CXX compiler identification is MSVC 19.38.33134.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.38.33130/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.38.33130/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- -------------------------------
-- Processing Project vk_ray_tracing__before_KHR:
CMake Error at CMakeLists.txt:20 (_add_project_definitions):
  Unknown CMake command "_add_project_definitions".

-- Configuring incomplete, errors occurred!

**Comment by mklefrancois** [comment]
Did you clone nvpro_core ? 
See setup: https://github.com/nvpro-samples/vk_raytracing_tutorial_KHR/blob/master/docs/setup.md

**Comment by Hoshino-Ruri** [comment]
> Did you clone nvpro_core ? See setup: https://github.com/nvpro-samples/vk_raytracing_tutorial_KHR/blob/master/docs/setup.md

I‘m stupid.Thank you.I found the problem.I just only cmake ray_tracing__before.Sorry waste your time.I have solved it.
