### ISSUE TITLE
Ray query sample does not work with beta driver 443.41

### ISSUE THREAD

**Issue by erymin** [nvpro-samples/vk_raytracing_tutorial_KHR#7]
Hi! It causes device lost. Something has been changed in spec?
With this driver I can't run my engine using inline ray query too.
Could you help or pass this issue to NV?
Thanks.

**Comment by mklefrancois** [comment]
Thanks for reporting, I will investigate the cause, meanwhile, please revert to the driver 443.24 
https://developer.nvidia.com/vulkan-beta-44324-windows-10-dch

**Comment by mklefrancois** [comment]
The newest driver 451.74 fixed the issue. 
https://developer.nvidia.com/vulkan-driver
