### ISSUE TITLE
Indirect Scissor readme has broken link

### ISSUE THREAD

**Issue by PinGunter** [nvpro-samples/vk_raytracing_tutorial_KHR#73]
The current Indirect Scissor readme has a broken href. It mixes html and markdown syntax and the github preview does not understand it. Meaning that if you want to access the tutorial you have to get the url from the raw readme.md instead of just clicking the link.

Currently is like this:
`[<h1>LINK TO FULL TUTORIAL</h1>](https://nvpro-samples.github.io/vk_raytracing_tutorial_KHR/vkrt_tuto_indirect_scissor.md.html)`

It should be like this:
`# [LINK TO FULL TUTORIAL](https://nvpro-samples.github.io/vk_raytracing_tutorial_KHR/vkrt_tuto_indirect_scissor.md.html)`

**Comment by NBickford-NV** [comment]
Thanks for the fix in #72! I've merged it in.
